name: gitworkflow

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    env:
      DBHOST: "localhost"
      PORT: 3000
      DBUSER: ${{ secrets.DBUSER }}
      DBPASS: ${{ secrets.DBPASS }}
      DATABASE: "csye6225"
      DBPORT: 3306
      CSV_PATH: "../users.csv"

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DBPASS }}
          MYSQL_DATABASE: "csye6225"
        ports:
          - 3306:3306 # Corrected the port
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Corrected the version

      - name: Use Node.js 18
        uses: actions/setup-node@v2 # Corrected the version
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests -- --detectOpenHandles
        run: npm test -- --detectOpenHandles
