name: gitworkflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  setup-nodejs:
    if: github.event.pull_request.head.repo.fork
    name: setup-nodejs
    runs-on: ubuntu-latest
    env:
      SERV_ADDR: "localhost"
      PORT: 3000
      MARIADB_CONNECTION_STRING: "mariadb://root:Root123#@localhost:3307/assign3_db"
      DB_NAME: "assign_db"
      USER_DATA_FILE_PATH: "./opt/users.csv"

    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: "Root123#"
          MARIADB_DATABASE: "assign3_db"
        ports:
          - 3307:3307
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
