name: Build ami on aws

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test_and_build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DBHOST: "localhost"
      PORT: 3000
      DBUSER: ${{ secrets.DBUSER }} # Using GitHub secrets
      DBPASS: ${{ secrets.DBPASS }} # Using GitHub secrets
      DATABASE: "csye6225"
      DBPORT: 3306
      CSV_PATH: "../users.csv"

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DBPASS }} # Using GitHub secrets
          MYSQL_DATABASE: "csye6225"
        ports:
          - 3306:3306 # Corrected the port
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    outputs:
      ami_id: ${{ steps.parse_ami_id.outputs.ami_id }}

    steps:
      - name: Github code checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v2 # Corrected the version
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests -- --detectOpenHandles
        run: npm test -- --detectOpenHandles

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build application artifact
        run: zip -r webapp.zip . -x ".git/*" ".gitignore" ".github/*"

      - name: Packer Init
        run: packer init packer-debian.pkr.hcl || exit 1
        working-directory: packer

      - name: Validate Packer Template
        run: packer validate packer-debian.pkr.hcl || (echo "Packer template validation failed!" && exit 1)
        working-directory: packer

      - name: Build AMI
        if: success()
        run: packer build -machine-readable -color=false -on-error=abort -var-file=dev.auto.pkrvars.hcl packer-debian.pkr.hcl | tee build.log
        working-directory: packer
        env:
          PACKER_LOG: 1

      - name: Parse AMI ID
        id: parse_ami_id
        working-directory: packer
        run: |
          AMI="$(grep 'artifact,0,id' build.log | cut -d, -f6 | cut -d: -f2)"
          echo "::set-output name=ami_id::$AMI"

      - name: Output AMI_ID
        env:
          AMI_ID: ${{ steps.parse_ami_id.outputs.ami_id }}
        run: |
          echo $AMI_ID

  dev:
    needs: test_and_build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      AMI_ID: ${{ needs.test_and_build.outputs.ami_id }}

    steps:
      - name: Create Dev launch template version
        run: |
          aws ec2 create-launch-template-version --launch-template-name my_launchTemplate --source-version 1 --launch-template-data '{"ImageId":"'"$AMI_ID"'"}' --debug

      - name: Update ASG to use the latest launch template version
        run: |
          LATEST_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-name my_launchTemplate --query "LaunchTemplateVersions[0].VersionNumber" --output text)
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name webapp_asg --launch-template "LaunchTemplateName=my_launchTemplate,Version=$LATEST_VERSION"

      - name: Start instance refresh
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name webapp_asg

      - name: Wait for instance refresh to complete
        run: |
          REFRESH_ID=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name webapp_asg --query "InstanceRefreshes[0].InstanceRefreshId" --output text)
          STATUS="Pending"
          while [[ "$STATUS" == "Pending" || "$STATUS" == "InProgress" ]]; do
            echo "Waiting for instance refresh to complete"
            sleep 60
            STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name webapp_asg --instance-refresh-ids $REFRESH_ID --query "InstanceRefreshes[0].Status" --output text)
            echo "Current status: $STATUS"
          done

          if [ "$STATUS" != "Successful" ]; then
            echo "Instance refresh failed with status: $STATUS"
            exit 1
          fi

  prod:
    needs: test_and_build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      AMI_ID: ${{ needs.test_and_build.outputs.ami_id }}

    steps:
      - name: Create Demo launch template version
        run: |
          aws ec2 create-launch-template-version --launch-template-name my_launchTemplate --source-version 1 --launch-template-data '{"ImageId":"'"$AMI_ID"'"}' --debug

      - name: Update ASG to use the latest launch template version
        run: |
          LATEST_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-name my_launchTemplate --query "LaunchTemplateVersions[0].VersionNumber" --output text)
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name webapp_asg --launch-template "LaunchTemplateName=my_launchTemplate,Version=$LATEST_VERSION"

      - name: Start instance refresh
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name webapp_asg

      - name: Wait for instance refresh to complete
        run: |
          REFRESH_ID=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name webapp_asg --query "InstanceRefreshes[0].InstanceRefreshId" --output text)
          STATUS="Pending"
          while [[ "$STATUS" == "Pending" || "$STATUS" == "InProgress" ]]; do
            echo "Waiting for instance refresh to complete"
            sleep 60
            STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name webapp_asg --instance-refresh-ids $REFRESH_ID --query "InstanceRefreshes[0].Status" --output text)
            echo "Current status: $STATUS"
          done

          if [ "$STATUS" != "Successful" ]; then
            echo "Instance refresh failed with status: $STATUS"
            exit 1
          fi
